resources:
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/traefik.containo.us_middlewaretcps.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.6/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml

patches:
  - patch: |-
      - op: replace
        path: "/subjects/0/namespace"
        value: traefik-system
    target:
      kind: ClusterRoleBinding
      version: v1
      name: traefik-ingress-controller
