resources:
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/traefik.containo.us_middlewaretcps.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v2.5.2/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
patchesStrategicMerge:
  - clusterrole.patch.yaml

patches:
  - patch: |-
      - op: replace
        path: "/apiVersion"
        value: rbac.authorization.k8s.io/v1
    target:
      group: rbac.authorization.k8s.io
      version: v1beta1
