apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sJX31CvD4HJ24k7rLdTPchD3b1UIWPRpsZBjme/MWmSUY5AuoAaJFPRuWhEpr0dDECNgXOiKjU2egyjkhGe9jLFeCf027SH0UHwI2HrwKpNOH6v1gX4xwq0zx1SFJ4dm8gpIu8G2kM0Wg1bQZ/u3HeCdFBuM8R+lsd4+l4XMxx3nKPMXfxYgzt4zxhj9aPOktEo5NABwtFXyjD1ie/12ed9kdjlN33ROOUWDGu/FUDPwQVgJ/Hy25ieyOpjqzqsScNYf/QpLSvzPkz+Kdt2gkNopbDBtHAeN1k8L86YNF+pYrGJBUVUpHBo4r3X3UhaaF38ItT8kFowpQFdxSpTDGxIkpkcP2BFdG03Xcn9Ha98IdoTI5mKYzfkm2xR/LMJajFMDN5kz7TCF8TImPOJ1aIUl,iv:iVHy1TID0wfF4eEHY2wslnAT8kR8NIOWboWD68zrqWQ=,tag:MToh4FlKypb/huRjmK1dKA==,type:str]
    identity.pub: ENC[AES256_GCM,data:PfEkifvPcqDfz+8pS2E0HeIVNwUFlBc9RgshEHuCKpJIJk0g0sJztfbYGtZ3D5rLs382Uzn6zPjh1zNMBieKXTTUejCYEqH5nsL+PSAx3p5YKumjrOOj4gER2p1Gdelty7fF4N1/Ce1u0hpQySHfzr3zrp4wbSKDfearFubNtTad1+E4j0xtMPFvILrPh6SwCyDDI/tLtQ44Cy8FAgvjMcjgdHShKLzelduU0+cO5TZeatg6HtZbzEtsvaWy0UuXD82brDR9X+vC4wErWA==,iv:euL7mL5TgeG8MHXWsp9okhqQ8xu3CPmmUCcHojMfCRM=,tag:O7cvF49TZ/4FnF0F6u8eqA==,type:str]
    known_hosts: ENC[AES256_GCM,data:eF30UKV7aGbnwIQvjyTF2WwbMhjUMA0hUSHiKfy300ffaYC3w9V+jVKH9RNL6zhEwKD+LBOhPxNuU6sUM7FWfUp6RiN+w4XG/cbqkos8z17FSZzo0CFjVFS/gy7K+DcXN4qh/sT9rTTbvf5lsORzTsU7DU+Vn6OjAjMx4VigzDlr5+RnUBp/fgsZwPa+dsTNYsyIu8kIXwXAt0WhiCu//Z40EmKkPuSARK9K,iv:gxtYgb2GgLvANDWlbKnVhYL3YAbET8lCJLQ6LD1Pojc=,tag:TRKfWXIsGt6l+pL46A9i4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-20T17:12:37Z"
    mac: ENC[AES256_GCM,data:+zqS5v9EuxZUyD75XZkxaQWJb4cqH3+63HKlFcXQaS7469RYqyCFZ2vk+o9NxnxUyNW4v2ay9svSByg4Zco3yU/kpgEuf/xgBHk9yGYv8MajuhxWWm5wj3DxcHnOmPHk/Qbzs82EfOTziY7po5bxCM0D90Ul93aHbLxSvoTBu78=,iv:LW4Z37yxE7X7jaquHlnJYISHa6dCByc4n4yFTq1H6l0=,tag:sjKD8ibQOgHb/laKNhJPlQ==,type:str]
    pgp:
        - created_at: "2021-11-20T17:12:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5JSBrarPrpaAQ/+PRYThHpKfD+JZ2Cj3p2Esblj1pqYkk9fS084Oh3o2kbg
            0O91fB17HH+WaVH5xWW5z0noTizh8DDmvW7P/L5hvGgBmJq/k/t2jAdHa5vRRxAE
            4Wg6El033PM0c/mmENB2nGJCDKVxfauHi9p6IpnNEXcNOWGEzhYh1HZcGqxggIl/
            LJfmXQAYSDyDa938smazXkiF3VnIzhgLtga8syHwLkGZkbVrsY8j4Mwt8vmO/sz/
            xLC7TV44qDTj7lQfYnrfmwp+X8QixKI//Vgv4d0jOKPOg8b6vONXt6cLdcaxVkoK
            Omh7Dhg5SRJ7USC/ocUdysrZXmrjzfaP3DvJ+mMGnEZrIx4r8oPoDTByGvBN88mh
            dcN3Dqf/D/PcHZl6V3gOG1R9qw4c0u+SSZnrlA5R3ToCUXlhryQSTBw+NMOrwvnd
            To9qM6KFkLgJCOe/Zd6ZkpSTQXrXF7UIfRuBId1EUZ0Kph/uYkYFtcxAnoeFShsr
            X8ad6QfRA0hFVjv9cY+B/kqcGL/pIOreTpeDOW1RkeWqIWB2ninbXqiXzBWQaRGS
            9sga+Iitpz1WepNZlgadMsf0DRjfbS0MyvOk/gloxuUtlG6z97i+E0QdcW/Cr7L2
            YSCA7iWZ7v8HDSCnoR0ZsynMUlFf1rxKQXJHDl7Ov95/yDHEkMQWcgcIOD1nWErU
            ZgEJAhALPYTZPb7qCz0njVQ4MfbQWS95vlQlB3UdINXE6JOqDB+OIbY3/sgw7Rxo
            4QJl9Km2AQhQ3lxFo8JA6DLgXSV1PgRdt6uHceQN29GAAc/UEtTPnpxDk7dLulBv
            tBNnUzbmqQ==
            =+uun
            -----END PGP MESSAGE-----
          fp: 69A1EBA51966811FFC0EF0D816BC706475C0C0FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
