apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: accounts
spec:
  commonName: accounts.${BASE_DOMAIN}
  secretName: accounts-certificate
  dnsNames:
    - accounts.${BASE_DOMAIN}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
