---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: accounts
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: "Host(`accounts.${BASE_DOMAIN}`) && PathPrefix(`/auth/`)"
      middlewares:
        - name: accounts-rewrite-users
      services:
        - name: keycloak
          scheme: https
          serversTransport: accounts
          port: 8443
    - kind: Rule
      match: "Host(`accounts.${BASE_DOMAIN}`)"
      middlewares:
        - name: accounts-redirect
  tls:
    secretName: accounts-certificate
