apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  instances: 1
  externalAccess:
    enabled: False
  migration:
    backups:
      enabled: true
  keycloakDeploymentSpec:
    resources:
      requests:
        memory: "600Mi"
        cpu: "300m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  postgresDeploymentSpec:
    resources:
      requests:
        memory: "600Mi"
        cpu: "50m"
      limits:
        memory: "1Gi"
        cpu: "100m"
  # multiAvailabilityZones:
  #   enabled: true
  # storageClassName: ""
