apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden
spec:
  dnsNames:
    - ${VAULTWARDEN_DOMAIN}
  secretName: vaultwarden-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
