apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-vaultwarden
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
  serviceName: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
    spec:
      containers:
        - name: mariadb-vaultwarden
          image: mariadb:11.3
          envFrom:
            - secretRef:
                name: mariadb-secrets
          env:
            - name: MYSQL_DATABASE
              value: vaultwarden
            - name: MYSQL_USER
              value: vaultwarden
          ports:
            - containerPort: 3306
              name: db
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
