---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: vaultwarden
  name: vaultwarden

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: vaultwarden
  name: vaultwarden
  namespace: vaultwarden

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: vaultwarden
  name: vaultwarden-reconciler
  namespace: vaultwarden
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:vaultwarden:reconciler
- kind: ServiceAccount
  name: vaultwarden
  namespace: vaultwarden

