apiVersion: v1
data:
    MAILU_DOMAIN1: ENC[AES256_GCM,data:vwmi0zk/+jpjlU2N4Mv4QM4/gOU=,iv:7voueGClycaQpeeXTMoK8Tq8FvsFK5ifKQgec/Zre3g=,tag:RY2eRFhHXzhfzrGBzGA1Vg==,type:str]
    MAILU_DOMAIN2: ENC[AES256_GCM,data:/SES7EfIrwDYBvtOsLS9KI47O8uxP2sf,iv:6PtN1mA26/fJ53hcPgzRkeFgX7gUdCBFmx/KBoVpNKI=,tag:eeKdjEO0zUFgMPw9iIpZZA==,type:str]
    MAILU_DOMAIN3: ENC[AES256_GCM,data:JIIcEITueVZAAJ+1,iv:NLtXSAwvfsgAU91puOY2/v9QuCphD89IYGhQ0DxMBTo=,tag:O5w3jGzVXvHHtTzRokAA5g==,type:str]
    MAILU_DOVEADM_PASSWORD: ENC[AES256_GCM,data:Q9rTRyVlHW0vfPu6DhJBApAtbfVAoqaxqMTYipPi2OJ88F/FsStq32tp2RnhHkSmw5WG+uFFGdM=,iv:ZK+1bxA3hAg4DSiwi4I9CuLQqSozhO0uQHs/UJiw5u0=,tag:E6WX+ksa0bLMuxXduaTAWA==,type:str]
    PERSONAL_CHANGECONNECTION_DOMAIN: ENC[AES256_GCM,data:756tUga3nsmEX3Sp0HjmAKHh7HKm+CsDQ9LQElSeqspWt8S6,iv:fVXmMpy6+IgRIcvPy5+hUAKwl3bEb82sSNYeG06vlKc=,tag:TZvNtsV3xE4fPR5ACckB3Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: apps-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-03T13:25:54Z"
    mac: ENC[AES256_GCM,data:7cDtKCJNvmJJgqn/M+vIg3hFcBvhFI72EK+/Ish9WxrA1/1uaZ9URbBfLbQzWz2f7skDwSjNLn/zbPYongFUnPnc/KvMmHegXAH4tE38yuDG/fpEz6XdAdS/eHAv+1U0mFrhSjh3OW+b/jCGh6PV/reJq6OipUj7i7ZKIYyLGlU=,iv:J+602lTqQ5nY0tlSrhmasZH6ZIqIz85tDOsO6opOzx8=,tag:YJIBc6HtGLgSn6KXSh3/XA==,type:str]
    pgp:
        - created_at: "2022-03-23T15:33:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5JSBrarPrpaAQ//SxvEr1d3ss9kZzrm8o/Mc2rurHNrKoMvG6UM+NopbjJO
            AEA8f4KyQKAPpCp7ITN/dCtoCsimj4e0c0dlaB8zf2+FH+ghM99ALGKatog7oDoO
            K2LTtcu6r4LDZ9TIaFfEwNH9gKhvc0sJCDKe9ZAwMwqlnvlsCmzkUIRkTEEYbJRZ
            yjIpcR7d/mDaJqRFEDLpnsPGwXacflo/2VvyaUMt5kHTgmwZ147wYUUWgvCADF4Q
            dLtpV81w4yWpwpb8XtumLEtt7aE1fPtqJV1I/N6AZ5xD0CLmzuJLKYp/WpMq978t
            DMO3Ks7BZYnbhOeSQD0ncTGRgPannXUEJikp3GFMEDzgijiPYmmRCHM8+/4NDw89
            cH2mDyrKBIzelp4HJAEwSus2X0dB0b0mHF9R3FX8BIIbZFG94rykLSP4GIfw3VP9
            /osALx6F5DL7hOHfG8J35bVnBlMRRvM9Wc7kdiyjztCsIIalcoSkw2wp1jLVCx2k
            ExoiuH/cWkSa28GawWR6Utbz5VbkfD462HRgeJWbQzW1Wgl2TspmM2Q2xmTp9sHH
            Xcm2ZiHPiqj+IcjDypR7LKqpO9aVtdfzgc6XlDYp8R2OQuoj5XqCv+XOzwJ/10JU
            AEBPiUyFNk+cZ7Ju8fvz7BhmQ4Uk7xILPjPOoItKA/oLxjJzNikI7HT24I5SQurU
            aAEJAhDpvQ1g2TWW7of6UzcpMdyQYl9zG7QuKiZ21MUjDUKXAxymjwuTsKt2R7T2
            kBVqDsQpH5fiDA5KsR4jXQ3RO4jEV7LaeViw5RRxzngWiQSMPq8UpawC6U+JQh+z
            dclHRD0vcCP7
            =2eVq
            -----END PGP MESSAGE-----
          fp: 69A1EBA51966811FFC0EF0D816BC706475C0C0FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
