---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: secret-apps
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: secret-apps
  url: ssh://git@github.com/fischerscode/secret-apps-contabo1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secret-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: secret-apps
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
