dependencies:
  - name: traefik
    type: github
    currentVersion: v2.5.2
    prefix: v
    repo: "traefik/traefik"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://github.com/traefik/traefik/blob/master/CHANGELOG.md)
  - name: metallb
    type: github
    currentVersion: v0.10.2
    prefix: v
    repo: "metallb/metallb"
    isTag: true
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [release-notes](https://metallb.universe.tf/release-notes)
  - name: PowerDNS auth
    type: github
    currentVersion: auth-4.5.1
    prefix: auth-
    repo: "PowerDNS/pdns"
    isTag: true
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://doc.powerdns.com/authoritative/changelog/)
  # - name: PowerDNS Admin
  - name: Rook
    type: github
    currentVersion: v1.7.0
    prefix: v
    repo: "rook/rook"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://github.com/rook/rook/releases)
  - name: CertManager
    type: github
    currentVersion: v1.5.3
    prefix: v
    repo: "jetstack/cert-manager"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://github.com/jetstack/cert-manager/releases)
  - name: keycloak-operator
    type: github
    currentVersion: "15.0.1"
    repo: "keycloak/keycloak-operator"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [Tags](https://github.com/keycloak/keycloak-operator/tags)
      [Keycloak Release Notes](https://www.keycloak.org/docs/latest/release_notes/)
  - name: k3s
    type: github
    currentVersion: "v1.21.4+k3s1"
    prefix: v
    repo: "k3s-io/k3s"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [k3s releases](https://github.com/k3s-io/k3s/releases)
      [Kubernetes Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/README.md)
  - name: grafana
    type: helm
    currentVersion: "6.16.10"
    repo: https://grafana.github.io/helm-charts
    chart: grafana
    issueBody: |
      Update $name from $currentVersion to $latestVersion.

      [Readme.md](https://github.com/grafana/helm-charts/blob/grafana-$latestVersion/charts/grafana/README.md)
      [Upgrading to new major version](https://github.com/grafana/helm-charts/blob/grafana-$latestVersion/charts/grafana/README.md#upgrading-an-existing-release-to-a-new-major-version)
  - name: prometheus-stack
    type: helm
    currentVersion: "19.0.1"
    repo: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    issueBody: |
      Update $name from $currentVersion to $latestVersion.

      [Readme.md](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-$latestVersion/charts/kube-prometheus-stack/README.md)
      [Upgrading to new major version](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-$latestVersion/charts/kube-prometheus-stack/README.md#upgrading-an-existing-release-to-a-new-major-version)
