dependencies:
  - name: traefik
    type: github
    currentVersion: v2.9.1
    prefix: v
    repo: "traefik/traefik"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://github.com/traefik/traefik/blob/master/CHANGELOG.md)
    issueLabels:
      - dependencies
      - uptodate
      - traefik
  - name: metallb
    type: github
    currentVersion: v0.14.5
    prefix: v
    repo: "metallb/metallb"
    isTag: true
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [release-notes](https://metallb.universe.tf/release-notes)
    issueLabels:
      - dependencies
      - uptodate
      - metallb
  - name: PowerDNS auth
    type: github
    currentVersion: auth-4.6.2
    prefix: auth-
    repo: "fischerscode/docker-PowerDNS"
    isTag: true
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://doc.powerdns.com/authoritative/changelog/)
    issueLabels:
      - dependencies
      - uptodate
      - powerdns
  - name: PowerDNS-Admin
    type: github
    currentVersion: admin-0.2.4
    prefix: admin-
    repo: "fischerscode/docker-PowerDNS"
    isTag: true
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://github.com/ngoduykhanh/PowerDNS-Admin/releases)
    issueLabels:
      - dependencies
      - uptodate
      - powerdns
  # - name: PowerDNS Admin
  - name: Rook
    type: github
    currentVersion: v1.12.11
    prefix: v
    repo: "rook/rook"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://github.com/rook/rook/releases)
      [Compare](https://github.com/rook/rook/compare/$currentVersion...$latestVersion)
    issueLabels:
      - dependencies
      - uptodate
      - rook
  - name: CertManager
    type: github
    currentVersion: v1.14.5
    prefix: v
    repo: "jetstack/cert-manager"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://github.com/jetstack/cert-manager/releases)
    issueLabels:
      - dependencies
      - uptodate
      - certmanager
  - name: keycloak-operator
    type: github
    currentVersion: "15.0.1"
    repo: "keycloak/keycloak-operator"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [Tags](https://github.com/keycloak/keycloak-operator/tags)
      [Keycloak Release Notes](https://www.keycloak.org/docs/latest/release_notes/)
    issueLabels:
      - dependencies
      - uptodate
      - keycloak
  - name: k3s
    type: github
    currentVersion: "v1.23.17+k3s1"
    prefix: v
    repo: "k3s-io/k3s"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [k3s releases](https://github.com/k3s-io/k3s/releases)
      [Kubernetes Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/README.md)
    issueLabels:
      - dependencies
      - uptodate
      - k3s
  - name: prometheus-stack
    type: helm
    currentVersion: "59.0.0"
    repo: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      **Make sure to also update the prometheus-operator CRDs!** (if needed)
      [Readme.md](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-$latestVersion/charts/kube-prometheus-stack/README.md)
      [Upgrading to new major version](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-$latestVersion/charts/kube-prometheus-stack/README.md#upgrading-an-existing-release-to-a-new-major-version)
    issueLabels:
      - dependencies
      - uptodate
      - monitoring
      - prometeus
  - name: prometheus-operator CRDs
    type: helm
    currentVersion: v0.74.0
    repo: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    prefix: v
    path: entries.kube-prometheus-stack.0.appVersion
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      Every file from [here](https://github.com/prometheus-operator/prometheus-operator/tree/$latestVersion/example/prometheus-operator-crd) should be in [here](infrastructure/base/crds/prometheus-operator/kustomization.yaml).
      **Make sure to also update the prometheus-stack!**
      [CHANGELOG.md](https://github.com/prometheus-operator/prometheus-operator/blob/$latestVersion/CHANGELOG.md)
      [RELEASE](https://github.com/prometheus-operator/prometheus-operator/releases/tag/$latestVersion)
    issueLabels:
      - dependencies
      - uptodate
      - monitoring
      - prometeus
  - name: grafana
    type: helm
    currentVersion: "7.3.10"
    repo: https://grafana.github.io/helm-charts
    chart: grafana
    issueBody: |
      Update used $name chart version from $currentVersion to $latestVersion.

      [Readme.md](https://github.com/grafana/helm-charts/blob/grafana-$latestVersion/charts/grafana/README.md)
      [Upgrading to new major version](https://github.com/grafana/helm-charts/blob/grafana-$latestVersion/charts/grafana/README.md#upgrading-an-existing-release-to-a-new-major-version)
    issueLabels:
      - dependencies
      - uptodate
      - monitoring
      - grafana
  - name: Loki
    type: helm
    currentVersion: "2.6.0"
    repo: https://grafana.github.io/helm-charts
    chart: loki
    issueBody: |
      Update used $name chart version from $currentVersion to $latestVersion.

      [Readme.md](https://github.com/grafana/helm-charts/blob/helm-loki-$latestVersion/charts/loki/README.md)
      [Upgrading](https://grafana.com/docs/loki/latest/setup/upgrade/)
    issueLabels:
      - dependencies
      - uptodate
      - monitoring
      - loki
  - name: Loki
    type: helm
    currentVersion: "3.8.1"
    repo: https://grafana.github.io/helm-charts
    chart: promtail
    issueBody: |
      Update used $name chart version from $currentVersion to $latestVersion.

      [Readme.md](https://github.com/grafana/helm-charts/blob/promtail-$latestVersion/charts/promtail/README.md)
      [Upgrading](https://github.com/grafana/helm-charts/blob/promtail-$latestVersion/charts/promtail/README.md#upgrading)
    issueLabels:
      - dependencies
      - uptodate
      - monitoring
      - promtail
  - name: Mailu
    type: github
    currentVersion: "2.0.41"
    repo: "Mailu/Mailu"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [Release $latestVersion](https://github.com/Mailu/Mailu/releases/tag/$latestVersion)
      [Changelog](https://github.com/Mailu/Mailu/compare/$currentVersion...$latestVersion)
    issueLabels:
      - dependencies
      - uptodate
      - mailu
      - mailserver
  - name: Mailu Helm chart
    type: helm
    currentVersion: "1.5.0"
    repo: https://mailu.github.io/helm-charts/
    chart: mailu
    issueBody: |
      Update used $name version from $currentVersion to $latestVersion.

      [Chart](https://mailu.github.io/helm-charts/)
    issueLabels:
      - dependencies
      - uptodate
      - mailu
      - mailu-chart
  - name: vaultwarden
    type: github
    currentVersion: "1.35.1"
    repo: "dani-garcia/vaultwarden"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.

      **Vaultwarden does not use semver! There might be breaking changes.**

      **Also consider updating [mariadb](https://hub.docker.com/_/mariadb)**

      [Release $latestVersion](https://github.com/dani-garcia/vaultwarden/releases/tag/$latestVersion)
      [Full Changelog](https://github.com/dani-garcia/vaultwarden/compare/$currentVersion...$latestVersion)
    issueLabels:
      - dependencies
      - uptodate
      - vaultwarden
