- name: Prepare the servers.
  hosts: all
  become: true
  gather_facts: false
  roles:
    - base
  tags:
    - base

- name: Setup WireGuard
  hosts: vpn
  roles:
    - vpn
  tags:
    - vpn

- name: Setup k3s
  hosts: k8s-cluster
  roles:
    - k3s
  tags:
    - k3s

- name: Restart masters
  hosts: kube-master
  serial: 1
  become: true
  tags:
    - k3s
  tasks:
    - name: Restart k3s
      import_role:
        name: restart_k3s
      when:
        - restart_k3s is defined
        - restart_k3s
- name: Restart workers
  hosts: kube-node
  serial: 1
  become: true
  tags:
    - k3s
  tasks:
    - name: Restart k3s
      import_role:
        name: restart_k3s
      when:
        - restart_k3s is defined
        - restart_k3s
