---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: dns
spec:
  entryPoints:
    - dns
  routes:
    - services:
        - name: "service"
          namespace: "namespace"
          port: 53
