---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dns
spec:
  entryPoints:
    - dns
  routes:
    - match: HostSNI(`*`)
      services:
        - name: "$(PDNS_SERVICE_DNS)"
          namespace: "$(PDNS_NAMESPACE)"
          port: 53
