resources:
  - namespace.yaml
  - mariadb-admin.yaml
  - mariadb-auth.yaml
  - pdns-auth.yaml
  - pdns-admin.yaml
  - pdns-auth-service.yaml
  # - pdns-admin-frontend.yaml

namePrefix: powerdns-

namespace: powerdns

vars:
  - name: PDNS_MARIADB_AUTH_NAME
    objref:
      kind: Service
      name: mariadb-auth
      apiVersion: v1
  - name: PDNS_MARIADB_ADMIN_NAME
    objref:
      kind: Service
      name: mariadb-admin
      apiVersion: v1
  - name: PDNS_API_HOST
    objref:
      kind: Service
      name: auth-api
      apiVersion: v1
  - name: PDNS_SERVICE_DNS
    objref:
      kind: Service
      name: dns
      apiVersion: v1
  - name: PDNS_NAMESPACE
    objref:
      kind: Namespace
      name: powerdns
      apiVersion: v1
  # - name: PDNS_ADMIN_HOST
  #   objref:
  #     kind: Service
  #     name: admin
  #     apiVersion: v1
