resources:
  - namespace.yaml
  - mariadb-admin.yaml
  - mariadb-auth.yaml
  - pdns-auth.yaml
  - pdns-admin.yaml
  - pdns-auth-service.yaml
  - dns-ingressroute-tcp.yaml
  - dns-ingressroute-udp.yaml
  # - pdns-admin-frontend.yaml

namePrefix: powerdns-

namespace: powerdns

replacements:
  - source:
      kind: Service
      name: mariadb-auth
    targets:
      - select:
          kind: Deployment
          name: auth
        fieldPaths:
          - spec.template.spec.containers.[name=auth].env.[name=PDNS_gmysql_host].value
  - source:
      kind: Service
      name: mariadb-admin
    targets:
      - select:
          kind: Deployment
          name: admin
        fieldPaths:
          - spec.template.spec.containers.[name=admin].env.[name=PDNS_ADMIN_SQLA_DB_HOST].value
  - source:
      kind: Service
      name: mariadb-admin
    targets:
      - select:
          kind: Deployment
          name: admin
        fieldPaths:
          - spec.template.spec.containers.[name=admin].env.[name=PDNS_ADMIN_SQLA_DB_HOST].value
  - source:
      kind: Service
      name: auth-api
    targets:
      - select:
          kind: Deployment
          name: admin
        fieldPaths:
          - spec.template.spec.containers.[name=admin].env.[name=PDNS_ENV_PDNS_webserver_host].value
  - source:
      kind: Service
      name: dns-tcp
    targets:
      - select:
          kind: IngressRouteTCP
          name: dns
        fieldPaths:
          - spec.routes.[match=HostSNI(`*`)].services.[port=53].name
  - source:
      kind: Service
      name: dns-tcp
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: IngressRouteTCP
          name: dns
        fieldPaths:
          - spec.routes.[match=HostSNI(`*`)].services.[port=53].namespace
  - source:
      kind: Service
      name: dns-udp
    targets:
      - select:
          kind: IngressRouteUDP
          name: dns
        fieldPaths:
          - spec.routes.[services.port=53].services.[port=53].name
  - source:
      kind: Service
      name: dns-udp
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: IngressRouteUDP
          name: dns
        fieldPaths:
          - spec.routes.[services.port=53].services.[port=53].namespace
# vars:
#   - name: PDNS_SERVICE_DNS
#     objref:
#       kind: Service
#       name: dns
#       apiVersion: v1
#   - name: PDNS_NAMESPACE
#     objref:
#       kind: Namespace
#       name: powerdns
#       apiVersion: v1
# - name: PDNS_ADMIN_HOST
#   objref:
#     kind: Service
#     name: admin
#     apiVersion: v1
