resources:
  - namespace.yaml
  - mariadb-admin.yaml
  - mariadb-auth.yaml
  - pdns-auth.yaml
  - pdns-admin.yaml
  - pdns-auth-service.yaml
  - dns-ingressroute-tcp.yaml
  - dns-ingressroute-udp.yaml
  - dashboard-route.yaml
  - dashboard-certificate.yaml
  - api-certificate.yaml
  - api-route.yaml

namePrefix: powerdns-

namespace: powerdns

replacements:
  - source:
      kind: Service
      name: mariadb-auth
    targets:
      - select:
          kind: Deployment
          name: auth
        fieldPaths:
          - spec.template.spec.containers.[name=auth].env.[name=PDNS_gmysql_host].value
  - source:
      kind: Service
      name: mariadb-admin
    targets:
      - select:
          kind: Deployment
          name: admin
        fieldPaths:
          - spec.template.spec.containers.[name=admin].env.[name=PDNS_ADMIN_SQLA_DB_HOST].value
  - source:
      kind: Service
      name: mariadb-admin
    targets:
      - select:
          kind: Deployment
          name: admin
        fieldPaths:
          - spec.template.spec.containers.[name=admin].env.[name=PDNS_ADMIN_SQLA_DB_HOST].value
  - source:
      kind: Service
      name: auth-api
    targets:
      - select:
          kind: Deployment
          name: admin
        fieldPaths:
          - spec.template.spec.containers.[name=admin].env.[name=PDNS_ENV_PDNS_webserver_host].value
      - select:
          kind: IngressRoute
          name: api
        fieldPaths:
          - spec.routes.0.services.[port=8081].name
  - source:
      kind: Service
      name: dns
    targets:
      - select:
          kind: IngressRouteTCP
          name: dns
        fieldPaths:
          - spec.routes.0.services.[port=53].name
      - select:
          kind: IngressRouteUDP
          name: dns
        fieldPaths:
          - spec.routes.0.services.[port=53].name
  - source:
      kind: Service
      name: dns
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: IngressRouteTCP
          name: dns
        fieldPaths:
          - spec.routes.0.services.[port=53].namespace
      - select:
          kind: IngressRouteUDP
          name: dns
        fieldPaths:
          - spec.routes.0.services.[port=53].namespace
  - source:
      kind: Certificate
      group: cert-manager.io
      name: dashboard
      fieldPath: spec.secretName
    targets:
      - select:
          kind: IngressRoute
          group: traefik.containo.us
          name: dashboard
        fieldPaths:
          - spec.tls.secretName
  - source:
      kind: Service
      name: admin
    targets:
      - select:
          kind: IngressRoute
          group: traefik.containo.us
          name: dashboard
        fieldPaths:
          - spec.routes.[kind=Rule].services.[name=admin].name

configurations:
  - kustomizeconfig.yaml
# vars:
#   - name: PDNS_SERVICE_DNS
#     objref:
#       kind: Service
#       name: dns
#       apiVersion: v1
#   - name: PDNS_NAMESPACE
#     objref:
#       kind: Namespace
#       name: powerdns
#       apiVersion: v1
# - name: PDNS_ADMIN_HOST
#   objref:
#     kind: Service
#     name: admin
#     apiVersion: v1
