apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: fischerscode/powerdns-admin:apikey-fix
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 9494
              protocol: TCP
          env:
            - name: PDNS_ADMIN_SQLA_DB_HOST
              value: "service"
            - name: PDNS_ADMIN_SQLA_DB_PORT
              value: "3306"
            - name: PDNS_ADMIN_SQLA_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DATABASE
                  name: mariadb-admin-config
            - name: PDNS_ADMIN_SQLA_DB_USER
              valueFrom:
                configMapKeyRef:
                  key: USER
                  name: mariadb-admin-config
            - name: PDNS_ADMIN_SQLA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: USER_PASSWORD
                  name: mariadb-admin-config
            - name: PDNS_ENV_PDNS_webserver_host
              value: "service"
            - name: PDNS_API_KEY
              valueFrom:
                secretKeyRef:
                  key: API_KEY
                  name: pdns-config
            - name: PDNS_ADMIN_SALT
              valueFrom:
                secretKeyRef:
                  key: SALT
                  name: pdns-admin-config
            - name: PDNS_ADMIN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: pdns-admin-config
            - name: PDNS_VERSION
              value: "4.5"
        - name: admin-frontend
          image: fischerscode/powerdns-admin-frontend:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PDNS_ADMIN_HOST
              value: "localhost"
            - name: PDNS_ADMIN_HOST_PORT
              value: "9494"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: admin
# spec:
#   selector:
#     app: admin
#   ports:
#     - port: 9494
#       targetPort: 9494
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  selector:
    app: admin
  ports:
    - port: 80
      targetPort: 80
