apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
