apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
spec:
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
        - name: admin-frontend
          image: fischerscode/powerdns-admin-frontend:test
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PDNS_ADMIN_HOST
              value: "$(PDNS_ADMIN_HOST)"
            - name: PDNS_ADMIN_HOST_PORT
              value: "9494"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
spec:
  selector:
    app: admin-frontend
  ports:
    - port: 80
      targetPort: 80
