bases:
  - ../../base/monitoring

namespace: monitoring

secretGenerator:
  - name: slack-webhook
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    files:
      - "URL=slack-webhook.encrypted"
  - name: grafana-cred
    namespace: monitoring
    options:
      disableNameSuffixHash: true
    literals:
      - "ADMIN_USER=admin"
    files:
      - "ADMIN_PASSWORD=grafana-admin-password.encrypted"

patchesStrategicMerge:
  - generated/prometheus-patch.yaml
