resources:
  - github.com/ArchiveFork/flux2-multi-tenancy/infrastructure/kyverno-policies?ref=b616f8b51aeb598da99cc05933085cf2b76999b0
patches:
  - path: excludes.patch.yaml
    target:
      version: v1
      group: kyverno.io
      kind: ClusterPolicy
      name: flux-multi-tenancy
