resources:
  - github.com/ArchiveFork/flux2-multi-tenancy/infrastructure/kyverno-policies?ref=c805ff03011c91793e101af4b2703a70e14d5d4d
patches:
  - path: excludes.patch.yaml
    target:
      version: v1
      group: kyverno.io
      kind: ClusterPolicy
      name: flux-multi-tenancy
