apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
        - name: cert-manager-cainjector
          resources:
            requests:
              cpu: 40m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
