---
bases:
  - ../../base/mailu

namespace: mailserver

secretGenerator:
  - name: mailu-secrets
    files:
      - secret-key=secret-key.encrypted
      - mariadb-root-password=mysql-root-password.encrypted
      - mariadb-password=mysql-mailu-password.encrypted
      - MYSQL_ROUNDCUBE_PASSWORD=mysql-roundcube-password.encrypted
      - MESSAGE_RATELIMIT_EXEMPTION=message-ratelimit-exemption.encrypted
