{
 "title": "Storage",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "persistentvolumeclaim",
    "label": "claim",
    "query": {
     "query": "label_values(kubelet_volume_stats_used_bytes{exported_namespace=~\"$namespace\"},persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ceph",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "Provisioned" },
    {
     "expr": "ceph_cluster_total_bytes - ceph_cluster_total_used_bytes",
     "legendFormat": "Availiable"
    }
   ]
  },
  {
   "title": "Ceph",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_cluster_total_used_bytes)",
     "legendFormat": "Provisioned"
    },
    {
     "expr": "sum(ceph_cluster_total_bytes - ceph_cluster_total_used_bytes)",
     "legendFormat": "Availiable"
    },
    { "expr": "sum(ceph_cluster_total_bytes)", "legendFormat": "Capacity" }
   ]
  },
  {
   "title": "PVC - Capacity",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{exported_namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}) by (persistentvolumeclaim, exported_namespace)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC - Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{exported_namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}) by (persistentvolumeclaim, exported_namespace)",
     "legendFormat": "{{exported_namespace}}: {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC - Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{exported_namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}) by (persistentvolumeclaim, exported_namespace) / max(kubelet_volume_stats_capacity_bytes{exported_namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}) by (persistentvolumeclaim, exported_namespace)",
     "legendFormat": "{{exported_namespace}}: {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC - Availiable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_available_bytes{exported_namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}) by (persistentvolumeclaim, exported_namespace) / max(kubelet_volume_stats_capacity_bytes{exported_namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}) by (persistentvolumeclaim, exported_namespace)",
     "legendFormat": "{{exported_namespace}}: {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC - Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{exported_namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}) by (persistentvolumeclaim, exported_namespace)",
     "legendFormat": "{{exported_namespace}}: {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC - Availiable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_available_bytes{exported_namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\"}) by (persistentvolumeclaim, exported_namespace)",
     "legendFormat": "{{exported_namespace}}: {{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}