{
 "title": "Traefik",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "requesthost", "query": ".*" },
   {
    "name": "internalTrafik",
    "label": "trafik",
    "query": "internal : true, external : false"
   },
   { "name": "entrypoint", "query": { "query": "label_values(entrypoint)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( max_over_time(traefik_geo_access_log_total{container=\"geologger\",namespace=\"traefik-system\",request_host=~\"$requesthost\",private_client_address=~\"$internalTrafik\"}[$__range]) - min_over_time(traefik_geo_access_log_total{container=\"geologger\",namespace=\"traefik-system\",request_host=~\"$requesthost\",private_client_address=~\"$internalTrafik\"} [$__range])) by (request_host) > 0",
     "legendFormat": "{{request_host}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        traefik_geo_access_log_total{container=\"geologger\",namespace=\"traefik-system\",request_host=~\"$requesthost\",private_client_address=~\"$internalTrafik\"}\n        [$__range])\n) by (request_host)",
     "legendFormat": "{{request_host}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum( max_over_time(traefik_geo_access_log_total{container=\"geologger\",namespace=\"traefik-system\",request_host=~\"$requesthost\",private_client_address=~\"$internalTrafik\"}[$__rate_interval]) - min_over_time(traefik_geo_access_log_total{container=\"geologger\",namespace=\"traefik-system\",request_host=~\"$requesthost\",private_client_address=~\"$internalTrafik\"} [$__rate_interval])) by (request_host) > 0",
     "legendFormat": "{{request_host}}"
    }
   ]
  },
  {
   "title": "Certificate expire data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "min(traefik_tls_certs_not_after{} - time()) by (cn)*1000",
     "legendFormat": "{{cn}}"
    },
    { "expr": "604800000", "legendFormat": "1w" },
    { "expr": "0", "legendFormat": "now" }
   ]
  },
  {
   "title": "Certificates that expire soon.",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(min(traefik_tls_certs_not_after{}) by (cn) < time() + 1209600) * 1000",
     "legendFormat": "{{cn}}"
    }
   ]
  },
  {
   "title": "Status code 200 over 5min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=\"200\"}[5m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Others status code over 5min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code!=\"200\"}[5m])",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "Total requests over 5min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{}[5m])) by (service)",
     "legendFormat": "Total requests {{service}}"
    }
   ]
  },
  {
   "title": "Average response time by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{protocol!=\"websocket\"}) by (service) / sum(traefik_service_request_duration_seconds_count{protocol!=\"websocket\"}) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "Average websocket lifetime by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{protocol=\"websocket\"}) by (service) / sum(traefik_service_request_duration_seconds_count{protocol=\"websocket\"}) by (service)",
     "legendFormat": " {{service}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum( max_over_time(traefik_geo_access_log_total{container=\"geologger\",namespace=\"traefik-system\",private_client_address=\"false\",geohash!=\"\", request_host=~\"$requesthost\"}[$__range]) - min_over_time(traefik_geo_access_log_total{container=\"geologger\",namespace=\"traefik-system\",private_client_address=\"false\",geohash!=\"\",request_host=~\"$requesthost\"} [$__range])) by (geohash, latitude, longitude) > 0"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum( max_over_time(traefik_geo_access_log_total{container=\"geologger\",namespace=\"traefik-system\",private_client_address=\"false\",geohash!=\"\", request_host=~\"$requesthost\"}[$__range]) - min_over_time(traefik_geo_access_log_total{container=\"geologger\",namespace=\"traefik-system\",private_client_address=\"false\",geohash!=\"\",request_host=~\"$requesthost\"} [$__range])) by (geohash, latitude, longitude) > 0"
    }
   ]
  },
  {
   "title": "World Map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "traffic from countries",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "valueName": "total",
     "targets": [
      {
       "expr": "sum by (iso_code) (count_over_time({container=\"geologger\",namespace=\"traefik-system\",stream=\"stdout\"} \n  | json iso_code=\"geolocation.country.iso_code\", \n         requesthost=\"RequestHost\", \n         privateClientAddress=\"privateClientAddress\" \n  | privateClientAddress=\"false\" \n  | requesthost=~\"$requesthost\" \n  | iso_code!=\"\" [$__interval]))",
       "legendFormat": "{{iso_code}}"
      }
     ]
    },
    {
     "title": "Traffic from geohash",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "valueName": "total",
     "targets": [
      {
       "expr": "sum by (geohash, position) (count_over_time({container=\"geologger\",namespace=\"traefik-system\",stream=\"stdout\"}\n  | json geohash=\"geolocation.location.geohash\", \n         longitude=\"geolocation.location.longitude\", \n         latitude=\"geolocation.location.latitude\", \n         requesthost=\"RequestHost\", \n         privateClientAddress=\"privateClientAddress\" \n  | privateClientAddress=\"false\" \n  | requesthost=~\"$requesthost\" \n  | geohash!=\"\" \n  | label_format position=\"{{.latitude}}, {{.longitude}}\" [$__interval]))"
      }
     ]
    }
   ]
  }
 ]
}