resources:
  - namespace.yaml
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml
  - ingressclass.yaml
  - dashboard-certificate.yaml
  - dashboard-auth.yaml
  - dashboard-route.yaml
  - pod-monitor.yaml
  - prometheus-rule.yaml

namespace: traefik-system

configMapGenerator:
  - name: traefik-config-static
    files:
      - config/traefik.yaml
  - name: grafana-dashboard
    options:
      labels:
        grafana-dashboard: "1"
    files:
      - traefik.json=dashboard.json

configurations:
  - kustomizeconfig/namereference.yaml

replacements:
  - source:
      name: traefik-dashboard-auth
      kind: Middleware
      fieldPath: metadata.namespace
    targets:
      - select:
          name: traefik-dashboard
          kind: IngressRoute
        fieldPaths:
          - spec.routes.[kind=Rule].middlewares.[name=traefik-dashboard-auth].namespace
