resources:
  - namespace.yaml
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml
  - ingressclass.yaml
  - dashboard-certificate.yaml
  - dashboard-auth.yaml
  - dashboard-route.yaml

namespace: traefik-system

configMapGenerator:
  - name: traefik-config-static
    files:
      - config/traefik.yaml

configurations:
  - kustomizeconfig/namereference.yaml
