---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: traefik
    - path: /
      port: metrics
  jobLabel: traefik
  selector:
    matchLabels:
      app: traefik
