apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: control-plane
spec:
  interfaces:
    - eth0
  ipAddressPools:
    - routing
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/control-plane: "true"
