apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: changedetection
spec:
  dnsNames:
    - changedetection.${BASE_DOMAIN}
  secretName: changedetection-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
