---
namespace: metallb-system

resources:
  - "github.com/metallb/metallb/config/prometheus-native?ref=v0.13.5"

configMapGenerator:
  - name: grafana-dashboard
    options:
      labels:
        grafana-dashboard: "1"
    files:
      - metallb.json=dashboard.json
