---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: apiserver
spec:
  entryPoints:
    - dns
  routes:
    - match: HostSNI(`*`)
      services:
        - name: "$(SERVICE)"
          namespace: "$(NAMESPACE2)"
          port: 53
