---
resources:
  - daemonset.yaml
  - service.yaml
  - ingressroute-tcp.yaml

namespace: kube-system

replacements:
  - source:
      kind: Service
      name: api-server-ha
    targets:
      - select:
          kind: IngressRouteTCP
          name: apiserver
        fieldPaths:
          - spec.routes.0.services.[port=6443].name
  - source:
      kind: Service
      name: api-server-ha
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: IngressRouteTCP
          name: apiserver
        fieldPaths:
          - spec.routes.0.services.[port=6443].namespace
