---
resources:
  - daemonset.yaml
  - service.yaml

namespace: kube-system

vars:
  - name: SERVICE
    objref:
      kind: Service
      name: api-server-ha
      apiVersion: v1
  - name: NAMESPACE2
    objref:
      kind: Service
      name: api-server-ha
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
