---
resources:
  - daemonset.yaml
  - service.yaml
  - ingressroute-tcp.yaml

namespace: kube-system

vars:
  - name: APILOADBALANCER_SERVICE
    objref:
      kind: Service
      name: api-server-ha
      apiVersion: v1
  - name: APILOADBALANCER_NAMESPACE
    objref:
      kind: Service
      name: api-server-ha
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
