---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  storage:
    useAllNodes: false
    useAllDevices: false
  healthCheck:
    startupProbe:
      osd:
        failureThreshold: 6
    livenessProbe:
      osd:
        failureThreshold: 30
