---
namespace: rook-ceph

bases:
  - dashboards

resources:
  - https://raw.githubusercontent.com/rook/rook/v1.8.0/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.8.0/deploy/examples/operator.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.8.0/deploy/examples/cluster.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.8.0/deploy/examples/csi/rbd/storageclass.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.8.0/deploy/examples/toolbox.yaml
  - service-monitors/csi-metrics.yaml
  - service-monitors/rook-ceph-mgr.yaml
  - filesystem.yaml
  - fs-storageclass.yaml
  - prometheus-rules.yaml

patchesStrategicMerge:
  - storageclass-patch.yaml
  - cluster-patch.yaml
