---
namespace: rook-ceph

bases:
  - dashboards

resources:
  - https://raw.githubusercontent.com/rook/rook/v1.7.6/cluster/examples/kubernetes/ceph/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.7.6/cluster/examples/kubernetes/ceph/operator.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.7.6/cluster/examples/kubernetes/ceph/cluster.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.7.6/cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.7.6/cluster/examples/kubernetes/ceph/toolbox.yaml
  - service-monitors/csi-metrics.yaml
  - service-monitors/rook-ceph-mgr.yaml
  - filesystem.yaml
  - fs-storageclass.yaml
  - prometheus-rules.yaml

patchesStrategicMerge:
  - storageclass-patch.yaml
  - cluster-patch.yaml
