---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rook-ceph.rules
spec:
  groups:
    - name: rook-ceph.rules
      rules:
        - alert: PVC-UsageHigh
          annotations:
            summary: "PVC '{{ $labels.persistentvolumeclaim }}' has little space left."
            description: "PVC '{{ $labels.persistentvolumeclaim }}' uses more then 80% of its capacity."
          expr: |
            max(kubelet_volume_stats_used_bytes{exported_namespace!=""}) by (persistentvolumeclaim, exported_namespace) / max(kubelet_volume_stats_capacity_bytes{exported_namespace!=""}) by (persistentvolumeclaim, exported_namespace) > 0.8
          for: 0m
          labels:
            severity: critical
