apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mailu
spec:
  commonName: mail.${MAILU_DOMAIN1}
  secretName: mailu-certificate
  dnsNames:
    - mail.${MAILU_DOMAIN1}
    - imap.${MAILU_DOMAIN1}
    - smtp.${MAILU_DOMAIN1}
    - mail.${MAILU_DOMAIN2}
    - imap.${MAILU_DOMAIN2}
    - smtp.${MAILU_DOMAIN2}
    - mail.${MAILU_DOMAIN3}
    - imap.${MAILU_DOMAIN3}
    - smtp.${MAILU_DOMAIN3}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
