---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
spec:
  interval: 5m
  serviceAccountName: mailserver

  valuesFrom:
    - kind: Secret
      name: mailu-secrets
      valuesKey: MESSAGE_RATELIMIT_EXEMPTION
      targetPath: limits.messageRatelimit.exemption

  chart:
    spec:
      chart: mailu
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: mailu
      interval: 5m
  values:
    global:
      database:
        roundcube:
          database: roundcube
          username: roundcube
          existingSecret: mailu-secrets
          existingSecretPasswordKey: MESSAGE_RATELIMIT_EXEMPTION

    hostnames:
      - mail.${MAILU_DOMAIN1}
      - imap.${MAILU_DOMAIN1}
      - smtp.${MAILU_DOMAIN1}
      - mail.${MAILU_DOMAIN2}
      - imap.${MAILU_DOMAIN2}
      - smtp.${MAILU_DOMAIN2}
      - mail.${MAILU_DOMAIN3}
      - imap.${MAILU_DOMAIN3}
      - smtp.${MAILU_DOMAIN3}

    domain: ${MAILU_DOMAIN1}

    existingSecret: mailu-secrets

    subnet: ${NETWORK_K8S_CLUSTER_CIDR}
    subnet6: ""

    networkPolicy:
      enabled: false

    mailuVersion: "2.0.10"

    logLevel: WARNING

    postmaster: admin

    recipientDelimiter: "+"

    limits:
      ## @param limits.messageSizeLimitInMegabytes Maximum size of an email in megabytes
      messageSizeLimitInMegabytes: 50

      authRatelimit:
        ip: 60/hour
        ipv4Mask: 24
        ipv6Mask: 56
        user: 100/day
        exemptionLength: 86400
        exemption: ""

      messageRatelimit:
        value: 200/day

    clusterDomain: ${NETWORK_K8S_CLUSTER_DOMAIN}

    ## @param letsencryptShortchain Controls whether we send the ISRG Root X1 certificate in TLS handshakes.
    ## This is required for android handsets older than 7.1.1 but slows down the performance of modern devices.
    letsencryptShortchain: false

    customization:
      siteName: "Mailu"
      website: "https://mail.maaeps.de"
      logoUrl: ""
      logoBackground: ""

    mariadb:
      enabled: true
      architecture: standalone

      auth:
        database: mailu
        username: mailu
        existingSecret: mailu-secrets

      primary:
        persistence:
          enabled: true
          size: 8Gi

    persistence:
      single_pvc: false

    ingress:
      enabled: true

      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        cert-manager.io/cluster-issuer: letsencrypt-prod

      tls: true

      realIpHeader: X-Forwarded-For
      realIpFrom: ${NETWORK_K8S_CLUSTER_CIDR}

      ## @param ingress.tlsFlavorOverride Overrides the value of `TLS_FLAVOR` environment variable in the `front` pod
      ## This is normally auto-detected, only change it if you know what you are doing.
      tlsFlavorOverride: ""

    front:
      hostPort:
        enabled: false
      externalService:
        enabled: false
      replicaCount: 1

    admin:
      enabled: true

    redis:
      enabled: true
      architecture: standalone

    dovecot:
      enabled: true
      persistence:
        size: 50Gi
      # resources:
      #   limits: {}
      #   requests: {}

    rspamd:
      overrides: {}
      antivirusAction: "discard"
      resources:
        limits: {}
        requests: {}

    ## @section clamav parameters
    clamav:
      enabled: false
      resources:
        limits: {}
        requests: {}

    ## @section webmail parameters
    webmail:
      enabled: true
      uri: /webmail
      roundcubePlugins:
        - archive
        - zipdownload
        - markasjunk
        - managesieve
        - enigma
        - carddav
        - mailu
      persistence:
        size: 20Gi
        storageClass: ""
        accessModes: [ReadWriteOnce]
        claimNameOverride: ""
        annotations: {}
      # resources:
      #   limits: {}
      #   requests: {}

    webdav:
      enabled: false

    fetchmail:
      enabled: false

    oletools:
      enabled: true
      # resources:
      #   limits: {}
      #   requests: {}
