namespace: mailserver

resources:
  - helm-repository.yaml
  - helm.yaml
  - rbac.yaml
  # - route-imap.yaml
  # - route-imaps.yaml
  # - route-pop3.yaml
  # - route-pop3s.yaml
  # - route-smtp.yaml
  # - route-smtps.yaml
  # - route-smtpd.yaml
  - ingress.yaml

configMapGenerator:
  - name: grafana-dashboard
    options:
      labels:
        grafana-dashboard: "1"
    files:
      - mailu.json=dashboard.json

configurations:
  - kustomizeconfig/namereference.yaml
