---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: routing
      protocol: layer2
      addresses:
      - ${SVC_KUBERNETES_API_PUBLIC}/32
      auto-assign: false
