apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:KjEJDTomMvkbILAbD0pg49MGYg1Q5yCG03TBhmlGQw1DdYHNoE30//DbxtBOY7b1xrnngfHuvdAKfcbuZH9pCXVBaHuT6tK91UqO59WAhGQ/qCF5+fnjKXplGFPFbumlaBAxu6IpWb2drQTM9PLPPgd7t/ZDsIIrhE0V+OFdGxqcbhkyMyu3i1/yG61GSLni/uK8Tpo4gvSYl6oFS/b4UwPcUyeyik7M0m9+ZA==,iv:ccQkywbUpHZ5B7W2hM4l/2smBmfCuEVpATibgwEANUo=,tag:A0fNlhQ2MEMtxpaKk5FGFw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: memberlist
    namespace: metallb-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-10T19:29:39Z"
    mac: ENC[AES256_GCM,data:+ZV3M9rFq/kteZb5EcPflZAw08i+o/g3mzK2lkTbftAMy9hp+Koh8BDJgT1t7CM3P5LBqOqRCu53JxIbVpavEU9bcFLsuEnLvIR4lNiAAD9/pVchm7OpEhEZJzMZ9t/hVPf6il/IwwMwNgYjqvjBxj1/AMylWTgx97RZIu1Qaag=,iv:jabdVyCqz4llD8v1Z7iP5mbY4c+vEaHQyxXAvhpJZiw=,tag:R6pvEekA9LYetW1GYYJFYQ==,type:str]
    pgp:
        - created_at: "2021-09-10T19:29:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3gUiB/FqGgjARAAowZuD8NGkL12WW9p8R45+C99WhRvOEMfdSdEDYl02vwo
            NiZtRoG37baSb1AW4ZJleaFJyxgCB6xUwor6YCxy0kwUEGKHNHezIRX9Y87+PzRc
            0JQPJ+c2GdiZh6JpOib7wtM79ksmVZtoji6XNj5sziQYWtRVBXOKfc4nKlUrKFXh
            RsvIAw7/s8LviBaQoVOwR8NP4UWCPArKrAv6FgYwl1UiFTBUjPaceVZbg16jz/Wn
            kRX56GlwCBlVr0F3pWMmfLqqzj/ucROZ0FPwXvXKn8teEPvT37E7WCFuppLWbl7L
            sJ2C48dMQ7sC3+bPjqXolgPgowdde2jLQ0nLdjN6W1el27jRV4TFA7FEIwOJ+WFX
            nmEmbIL+FFlixtI0JBs6rPSFadxeErkladv6cX11vvtWdWKJIZAkGr5Rwjyjm5ou
            rW31AxM1QJruttfu9qeVx4LkSlc8UeI4ZSNopl/vAS0xYmWEUOiMGUaV6CSqzKvE
            h/8wi0Wj2OuaytvTeaqUFGT1qPrLE9W1JzURgz6R0hWHa0CRkip1dZttGISR4Jca
            X80TuqxP5yTP1el/biXszPl/gli8fH0yTIeU/iEqHUbCDq8ecE56u9GNPyQeM2QM
            NTU8SW75V3RKDD4WRHFKTKA4d5hUnK1TrreQ+bujixwS2mjAXbdywPakcImvoPDU
            aAEJAhXgthJGSgLK3SQRbxTu7mCSCRWuaSET/BegfUBR2jcdmuBrwKGjDurgp4MG
            vr+JsJ8OF4DbGtic2aq5ULm72edr8k1hXfs7VLeNnzszjDr73dIRJYds03pwKWqT
            xpgGuADxsr50
            =Ri9F
            -----END PGP MESSAGE-----
          fp: 34461D8808A76061B6DF01FCE4BDAAFB057F6DEA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
