---
- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure basic packages
  apt:
    name:
      - byobu
      - zsh
      - curl
      - wget
      - dnsutils
      - git
      - sudo
      - htop
      - vim
      - nano
      - net-tools
    state: present

- name: Ensure clean motd
  file:
    path: "/etc/update-motd.d/{{item}}"
    state: absent
  with_items:
    - 10-help-text
    - 50-motd-news
    - 80-esm
    - 80-livepatch

- name: Ensure clean motd, news updater doesn't run
  systemd:
    name: motd-news
    enabled: no
    masked: yes

- name: Ensure notice about configuration managment in motd
  copy:
    content: |
      #!/bin/sh
      printf "\n"
      printf "This system is managed with ansible, see following repository for details\n"
      printf "{{ REPOSITORY }}\n"
      printf "\n"
    mode: 0755
    dest: /etc/update-motd.d/11-help-text

- name: Ensure that LANG from ssh clients is not used
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "AcceptEnv LANG LC_*"
    state: absent
  notify: restart sshd

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- import_tasks: firewall.yml

- import_tasks: users.yml
- import_tasks: sshd.yml
