---
- name: Ensure 'sudo' group exists
  group:
    name: sudo
    state: present

- name: Create users
  user:
    name: '{{ item.name }}'
    shell: /bin/bash
    password: '!'
    update_password: on_create
    groups:
      - sudo
    state: present
  with_items: '{{ users }}'

- name: Add SSH keys
  authorized_key:
    user: '{{ item.name }}'
    state: present
    key: '{{ item.sshkeys }}'
  with_items: '{{ users }}'

- name: Ensure sudo group is passwordless
  lineinfile:
    path: /etc/sudoers.d/sudo-nopasswd
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: '/usr/sbin/visudo -cf %s'

- name: Ensure sudoers uses sudoers.d
  lineinfile:
    path: /etc/sudoers
    line: '#includedir /etc/sudoers.d'
    state: present
    validate: '/usr/sbin/visudo -cf %s'