---
- name: Get the kubeconfig
  hosts: "{{ groups['kube-master'][0] }}"
  tasks:
    - fetch:
        flat: yes
        src: /etc/rancher/k3s/k3s.yaml
        dest: "../kubeconfig-{{ cluster_name }}.yaml"
      become: true
