global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: false
          priority: 1
  https:
    address: :443
    http:
      tls: {}
  kubeapi:
    address: :6443
  dns-tcp:
    address: :53
  dns-udp:
    address: :53/udp
  pop3:
    address: :110
  pop3s:
    address: :995
  imap:
    address: :143
  imaps:
    address: :993
  smtp:
    address: :25
  smtps:
    address: :465
  smtpd:
    address: :587

providers:
  kubernetesCRD:
    allowExternalNameServices: true
  kubernetesIngress: {}
api:
  dashboard: true
  insecure: true
ping:
  entryPoint: http
log:
  level: INFO

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

accessLog:
  format: json
  filePath: "/var/log/access.log"
