global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: false
          priority: 1
  https:
    address: :443
    http:
      tls: {}
  kubeapi:
    address: :6443
  dns-tcp:
    address: :53
  dns-udp:
    address: :53/udp

providers:
  kubernetesCRD: {}
  kubernetesIngress: {}
api:
  dashboard: true
  insecure: true
ping:
  entryPoint: http
log:
  level: INFO
