---
bases:
  - ../../base/vaultwarden

namespace: vaultwarden

secretGenerator:
  - name: vaultwarden-secrets
    files:
      - PUSH_INSTALLATION_ID=push-installation-id.encrypted
      - PUSH_INSTALLATION_KEY=push-installation-key.encrypted
      - ADMIN_TOKEN=admin-token.encrypted
      - SMTP_PASSWORD=smtp-password.encrypted
      - DATABASE_URL=database-url.encrypted
  - name: mariadb-secrets
    files:
      - MARIADB_ROOT_PASSWORD=mariadb-root-password.encrypted
      - MARIADB_PASSWORD=mariadb-password.encrypted
