name: update-traefik

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  crds:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: repo

      - name: get latest traefik release
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/traefik/traefik/releases/latest | jq '.tag_name' | sed 's/\"//g')"
          BODY=$(curl -s https://api.github.com/repos/traefik/traefik/releases/latest | jq -r '.body' | sed "s/\"/'/g")
          BODY="${BODY//'%'/'%25'}"
          BODY="${BODY//$'\n'/'%0A'}"
          BODY="${BODY//$'\r'/'%0D'}"
          echo "::set-output name=body::$BODY"
      - name: Latest traefik release
        run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}
      - name: checkout traefik
        uses: actions/checkout@v3
        with:
          repository: traefik/traefik
          ref: ${{ steps.latestrelease.outputs.releasetag }}
          path: traefik

      - name: Copy traefik config
        run: |
          cp traefik/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutes.yaml       repo/infrastructure/base/crds/traefik/resources/ingressroutes.yaml
          cp traefik/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressroutetcps.yaml    repo/infrastructure/base/crds/traefik/resources/ingressroutetcps.yaml
          cp traefik/docs/content/reference/dynamic-configuration/traefik.containo.us_ingressrouteudps.yaml    repo/infrastructure/base/crds/traefik/resources/ingressrouteudps.yaml
          cp traefik/docs/content/reference/dynamic-configuration/traefik.containo.us_middlewares.yaml         repo/infrastructure/base/crds/traefik/resources/middlewares.yaml
          cp traefik/docs/content/reference/dynamic-configuration/traefik.containo.us_middlewaretcps.yaml      repo/infrastructure/base/crds/traefik/resources/middlewaretcps.yaml
          cp traefik/docs/content/reference/dynamic-configuration/traefik.containo.us_serverstransports.yaml   repo/infrastructure/base/crds/traefik/resources/serverstransports.yaml
          cp traefik/docs/content/reference/dynamic-configuration/traefik.containo.us_tlsoptions.yaml          repo/infrastructure/base/crds/traefik/resources/tlsoptions.yaml
          cp traefik/docs/content/reference/dynamic-configuration/traefik.containo.us_tlsstores.yaml           repo/infrastructure/base/crds/traefik/resources/tlsstores.yaml
          cp traefik/docs/content/reference/dynamic-configuration/traefik.containo.us_traefikservices.yaml     repo/infrastructure/base/crds/traefik/resources/traefikservices.yaml
          cp traefik/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml                      repo/infrastructure/base/crds/traefik/resources/rbac.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: repo
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-traefik
          commit-message: Update Traefik to ${{ steps.latestrelease.outputs.releasetag }}
          title: Update Traefik to ${{ steps.latestrelease.outputs.releasetag }}
          body: |
            ${{ steps.latestrelease.outputs.body }}
          assignees: fischerscode
          reviewers: fischerscode
          delete-branch: true
