name: uptodate

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fischerscode/uptodate@v0.3
